// <auto-generated />
namespace wompsmash.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class contact_fixed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contact_fixed));
        
        string IMigrationMetadata.Id
        {
            get { return "201506241012113_contact_fixed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
